[package]
name = "deployer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-utils = "0.17.0"
ic-agent = "0.17.0"
ring = "0.16.20"
pem = "1.0.2"
base64 = "0.13.0"