[package]
name = "tests"
version = "0.1.0"
publish = false
edition = "2021"


[dev-dependencies]
ic-agent = "0.22.0"
tokio-test = "0.4.2"
candid = "0.7.14"
serde = "1.0"
chat_canister = { path = "../chat_canister" }

[[test]]
name = "test"
path = "test_import_export.rs"